### ISSUE TITLE
Wrong date offset from "expected" file

### ISSUE THREAD

**Issue by szwowo** [mongounit/mongounit#19]
Hi,
I made an Integration Test with mongounit. In my "expected" file I have date field `start` with date value `"$$DATE_TIME": "2021-02-15T10:00:00.000Z"`.
When I run this test on my local environment there is an error `Field name 'start': Expected '1613379600000' but got '1613383200000'`.

`1613383200000` is `2021-02-15T10:00:00.000Z` which is what I expect. It seems like mongounit converts date from expected file to my local timezone. 

Is there a way to configure this? I have added property `mongounit.local-time-zone-id=UTC` but it changes nothing.

Thanks

**Comment by szwowo** [comment]
Nevermind, it was not coused by mongounit. Sorry :)

**Comment by ychaikin** [comment]
@szwowo Ha! I was just about to try to set up a test to make sure it worked. Thanks for getting back and closing the issue!
