### ISSUE TITLE
$$DATE_TIME using local timezone instead of UTC

### ISSUE THREAD

**Issue by coney** [mongounit/mongounit#25]
I have a json seed  with a datetime field `"$$DATE_TIME": "2021-08-03T03:25:27.138Z"`, And my local timezone is UTC+8. After the json had been inserted to Mongo, The datetime turned to be `2021-08-02T19:25:27.138+00:00`. 

From the code snippet I found that mongounit doesn't set the timezone for SimpleDateFormatter and the formatter doesn't respect the `Z` suffix. It uses my local timezone to parse the date string:

https://github.com/mongounit/mongounit/blob/fe727bc81de4500515424bb1165514236fb03689/src/main/java/org/mongounit/MongoUnitUtil.java#L450

The debug screenshort with value evaluation is listed below(CST stands for UTC+8):

![image](https://user-images.githubusercontent.com/3133778/144066985-4f038b51-b582-4aa1-acc3-67d9b86509aa.png)

**Comment by lrozek** [comment]
To fix it string format should be changed to `yyyy-MM-dd'T'HH:mm:ss.SSSX` in
https://github.com/mongounit/mongounit/blob/fe727bc81de4500515424bb1165514236fb03689/src/main/java/org/mongounit/MongoUnitUtil.java#L81
More info at: https://stackoverflow.com/a/24394069
