### ISSUE TITLE
Add Support For UUID type

### ISSUE THREAD

**Issue by thanasisKirmizis** [mongounit/mongounit#41]
Currently there is no way to generate data that contain IDs of type UUID, only ObjectID is supported. This type could be added (e.g. `"_id": {"$$UUID": "e84f1bc2-c40e-46b9-bd7d-1a73a1c4e74e" }` ), in order to expand the supported types and help projects that already use UUID work with mongounit.

**Comment by ychaikin** [comment]
Thank you for the MR contribution! Much appreciated!
